"""
Lung Cancer Risk Prediction — XAI Clinical Dashboard
=====================================================
Place this file at:  app/streamlit_app.py
Run with:           streamlit run app/streamlit_app.py
 
Required files (generated by the pipeline):
  app/model/final_model.pkl
  app/model/shap_explainer.pkl
  app/model/feature_meta.json
  app/model/slider_config.json
 
Optional files (generated by phase6_calibration_fairness.py):
  outputs/calibration/P1_calibration_summary.json
  outputs/calibration/P1_calibration_curves.png
  outputs/fairness/P3_subgroup_metrics.csv
  outputs/fairness/P3_subgroup_performance.png
  outputs/fairness/P3_equity_gaps.json
"""
 
import json
import os
import warnings
warnings.filterwarnings("ignore")
 
import joblib
import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
 
try:
    import shap
    SHAP_OK = True
except ImportError:
    SHAP_OK = False
 
# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Lung Cancer Risk · XAI Dashboard",
    page_icon="🫁",
    layout="wide",
    initial_sidebar_state="expanded",
)
 
# ── Helper: risk tier ─────────────────────────────────────────────────────────
def get_tier(prob):
    if prob > 0.62:
        return "CRITICAL", "danger", "#f85149", "Immediate referral for Low-Dose CT (LDCT)"
    elif prob > 0.48:
        return "MODERATE", "moderate", "#d29922", "Short-term follow-up (3–6 months)"
    else:
        return "LOW", "low", "#3fb950", "Routine annual screening"
 
# ── Custom CSS ────────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Sans:wght@300;400;500;700&display=swap');
 
:root {
    --bg:        #0d1117;
    --surface:   #161b22;
    --border:    #21262d;
    --accent:    #58a6ff;
    --danger:    #f85149;
    --warn:      #d29922;
    --safe:      #3fb950;
    --text:      #e6edf3;
    --muted:     #8b949e;
    --font-body: 'DM Sans', sans-serif;
    --font-mono: 'DM Mono', monospace;
}
 
html, body, [class*="css"] {
    font-family: var(--font-body);
    background-color: var(--bg);
    color: var(--text);
}
 
[data-testid="stSidebar"] {
    background-color: var(--surface) !important;
    border-right: 1px solid var(--border);
}
[data-testid="stSidebar"] * { color: var(--text) !important; }
 
/* ── Priority 2: Top warning banner ── */
.top-warning-banner {
    background: rgba(210,153,34,0.10);
    border: 1px solid rgba(210,153,34,0.40);
    border-left: 4px solid #d29922;
    border-radius: 8px;
    padding: 14px 20px;
    margin-bottom: 20px;
    font-size: 0.82rem;
    color: #d29922;
    line-height: 1.6;
}
.top-warning-banner strong { color: #d29922; }
 
.header-strip {
    background: linear-gradient(135deg, #0d1117 0%, #1a2332 50%, #0d1117 100%);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 24px 32px;
    margin-bottom: 16px;
    position: relative;
    overflow: hidden;
}
.header-strip::before {
    content: '';
    position: absolute;
    top: -50%; left: -10%;
    width: 40%; height: 200%;
    background: radial-gradient(ellipse, rgba(88,166,255,0.06) 0%, transparent 70%);
    pointer-events: none;
}
.header-title {
    font-size: 1.8rem; font-weight: 700;
    letter-spacing: -0.02em; margin: 0 0 4px 0;
    color: var(--text);
}
.header-sub {
    font-family: var(--font-mono); font-size: 0.75rem;
    color: var(--muted); letter-spacing: 0.08em; text-transform: uppercase;
}
 
.risk-card {
    border-radius: 12px; padding: 28px;
    text-align: center; border: 1px solid var(--border);
}
.risk-card.critical { background: rgba(248,81,73,0.08);  border-color: var(--danger); }
.risk-card.moderate { background: rgba(210,153,34,0.08); border-color: var(--warn); }
.risk-card.low      { background: rgba(63,185,80,0.08);  border-color: var(--safe); }
 
.risk-label { font-family: var(--font-mono); font-size: 0.65rem; letter-spacing: 0.15em; text-transform: uppercase; margin-bottom: 8px; }
.risk-score { font-size: 3.2rem; font-weight: 700; letter-spacing: -0.03em; line-height: 1; }
.risk-tier  { font-size: 0.95rem; font-weight: 500; margin-top: 8px; letter-spacing: 0.04em; }
.risk-action { font-size: 0.78rem; color: var(--muted); margin-top: 10px; line-height: 1.5; }
 
/* ── Priority 2: Score caption under risk card ── */
.score-uncertainty {
    background: rgba(88,166,255,0.06);
    border: 1px solid rgba(88,166,255,0.15);
    border-radius: 6px;
    padding: 8px 12px;
    font-size: 0.74rem;
    color: var(--muted);
    margin-top: 10px;
    line-height: 1.5;
    text-align: center;
}
 
.section-title {
    font-family: var(--font-mono); font-size: 0.65rem;
    letter-spacing: 0.15em; text-transform: uppercase;
    color: var(--muted); border-bottom: 1px solid var(--border);
    padding-bottom: 8px; margin: 24px 0 16px 0;
}
 
.metric-row {
    display: flex; justify-content: space-between; align-items: center;
    padding: 10px 0; border-bottom: 1px solid var(--border); font-size: 0.88rem;
}
.metric-row:last-child { border-bottom: none; }
.metric-name { color: var(--muted); }
.metric-val  { font-family: var(--font-mono); font-weight: 500; }
.metric-delta-pos { color: var(--danger); font-size: 0.75rem; }
.metric-delta-neg { color: var(--safe);   font-size: 0.75rem; }
 
/* ── Priority 2: SHAP uncertainty note ── */
.shap-uncertainty {
    background: rgba(139,148,158,0.07);
    border: 1px solid rgba(139,148,158,0.15);
    border-radius: 6px;
    padding: 8px 12px;
    font-size: 0.74rem;
    color: var(--muted);
    margin-top: 8px;
    line-height: 1.5;
}
 
/* ── Priority 1 & 3: Analysis tab cards ── */
.analysis-card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 20px;
    margin-bottom: 16px;
}
.brier-badge {
    display: inline-block;
    font-family: var(--font-mono);
    font-size: 1.4rem;
    font-weight: 700;
    padding: 8px 16px;
    border-radius: 8px;
    margin: 8px 0;
}
.brier-good { background: rgba(63,185,80,0.12); color: #3fb950; border: 1px solid rgba(63,185,80,0.3); }
.brier-ok   { background: rgba(210,153,34,0.12); color: #d29922; border: 1px solid rgba(210,153,34,0.3); }
.brier-poor { background: rgba(248,81,73,0.12);  color: #f85149; border: 1px solid rgba(248,81,73,0.3); }
 
/* ── What-If counterfactual section ── */
.whatif-ref-card {
    background: rgba(88,166,255,0.06);
    border: 1px solid rgba(88,166,255,0.2);
    border-radius: 12px;
    padding: 20px;
    text-align: center;
    margin-bottom: 12px;
}
.delta-improve { color: #3fb950; font-size: 1.8rem; font-weight: 700; text-align: center; }
.delta-worsen  { color: #f85149; font-size: 1.8rem; font-weight: 700; text-align: center; }
.delta-neutral { color: #8b949e; font-size: 1.8rem; font-weight: 700; text-align: center; }
.intervention-note {
    background: rgba(63,185,80,0.06);
    border: 1px solid rgba(63,185,80,0.2);
    border-radius: 8px;
    padding: 12px 16px;
    font-size: 0.82rem;
    color: #d29922;
    margin-top: 12px;
    line-height: 1.6;
}

[data-testid="stSlider"] div[role="slider"] {
    background: var(--accent) !important;
    border-color: var(--accent) !important;
}
label { color: var(--muted) !important; font-size: 0.82rem !important; }
.st-emotion-cache-111apq > div {
    background: transparent !important;
    border: none !important;
    padding: 0 !important;
    background-color: transparent !important;
    box-shadow: none !important;
}

[data-testid="stSlider"] [class*="st-emotion-cache"] {
    background: transparent !important;
    background-color: transparent !important;
    border: none !important;
    box-shadow: none !important;
}         

/* ── Selectbox / dropdown legibility ── */
[data-baseweb="select"] > div {
    background-color: var(--surface) !important;
    border-color: var(--border) !important;
}
[data-baseweb="select"] *,
[data-baseweb="select"] span,
[data-baseweb="select"] div,
[data-baseweb="select"] input {
    color: var(--text) !important;
}
[data-baseweb="placeholder"] {
    color: var(--muted) !important;
}
[data-baseweb="popover"],
[data-baseweb="popover"] ul,
[data-baseweb="menu"] {
    background-color: var(--surface) !important;
    border: 1px solid var(--border) !important;
}
[data-baseweb="option"] {
    background-color: var(--surface) !important;
    color: var(--text) !important;
}
[data-baseweb="option"]:hover,
[data-baseweb="option"][aria-selected="true"] {
    background-color: var(--border) !important;
    color: var(--accent) !important;
}
li[role="option"] {
    background-color: var(--surface) !important;
    color: var(--text) !important;
}
li[role="option"]:hover {
    background-color: var(--border) !important;
}
.stButton > button {
    background: var(--accent) !important; color: #0d1117 !important;
    border: none !important; border-radius: 8px !important;
    font-weight: 600 !important; letter-spacing: 0.03em !important;
    padding: 0.55rem 1.4rem !important; transition: opacity 0.15s;
}
.stButton > button:hover { opacity: 0.85 !important; }
[data-testid="stExpander"] details[open] summary {
    background-color: rgba(88, 166, 255, 0.08) !important;
    border-color: #58a6ff !important;
    color: #58a6ff !important;
}

div[data-testid="metric-container"] {
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 8px; padding: 12px 16px;


}
 
/* ── Priority 2: Footer disclaimer ── */
.disclaimer {
    background: rgba(210,153,34,0.06);
    border: 1px solid rgba(210,153,34,0.25);
    border-radius: 8px; padding: 12px 16px;
    font-size: 0.78rem; color: var(--muted);
    margin-top: 32px; line-height: 1.6;
}
</style>
""", unsafe_allow_html=True)
 
# ── File paths ─────────────────────────────────────────────────────────────────
MODEL_DIR      = os.path.join(os.path.dirname(__file__), "app", "model")
MODEL_PATH     = os.path.join(MODEL_DIR, "final_model.pkl")
EXPLAINER_PATH = os.path.join(MODEL_DIR, "shap_explainer.pkl")
META_PATH      = os.path.join(MODEL_DIR, "feature_meta.json")
SLIDER_PATH    = os.path.join(MODEL_DIR, "slider_config.json")
 
# Priority 1 & 3 output paths (optional — produced by phase6_calibration_fairness.py)
CAL_SUMMARY_PATH   = "outputs/calibration/P1_calibration_summary.json"
CAL_CURVE_PATH     = "outputs/calibration/P1_calibration_curves.png"
FAIRNESS_CSV_PATH  = "outputs/fairness/P3_subgroup_metrics.csv"
FAIRNESS_PLOT_PATH = "outputs/fairness/P3_subgroup_performance.png"
EQUITY_GAP_PATH    = "outputs/fairness/P3_equity_gaps.json"
 
# ── Load assets (cached) ──────────────────────────────────────────────────────
@st.cache_resource(show_spinner="Loading model…")
def load_model():
    return joblib.load(MODEL_PATH)
 
@st.cache_resource(show_spinner="Loading explainer…")
def load_explainer():
    if SHAP_OK and os.path.exists(EXPLAINER_PATH):
        return joblib.load(EXPLAINER_PATH)
    return None
 
@st.cache_data
def load_meta():
    with open(META_PATH, "r") as f:
        return json.load(f)
 
@st.cache_data
def load_slider_config():
    with open(SLIDER_PATH, "r") as f:
        return json.load(f)
 
@st.cache_data
def load_calibration_summary():
    if os.path.exists(CAL_SUMMARY_PATH):
        with open(CAL_SUMMARY_PATH) as f:
            return json.load(f)
    return None
 
@st.cache_data
def load_fairness_data():
    df   = pd.read_csv(FAIRNESS_CSV_PATH)  if os.path.exists(FAIRNESS_CSV_PATH)  else None
    if os.path.exists(EQUITY_GAP_PATH):
        with open(EQUITY_GAP_PATH) as f:
            gaps = json.load(f)
    else:
        gaps = None
    return df, gaps
 
# ── Graceful missing-file check ────────────────────────────────────────────────
required = [MODEL_PATH, META_PATH, SLIDER_PATH]
missing  = [p for p in required if not os.path.exists(p)]
if missing:
    st.error("**Missing model files.** Run the pipeline first to generate:")
    for p in missing:
        st.code(p)
    st.stop()
 
model      = load_model()
explainer  = load_explainer()
meta       = load_meta()
slider_cfg = load_slider_config()
 
features    = meta["features"]
threshold   = meta.get("threshold", 0.40)
avg_patient = meta.get("average_patient", {})
 
cal_summary         = load_calibration_summary()
fairness_df, equity_gaps = load_fairness_data()
 
# ── Sample patients ────────────────────────────────────────────────────────────
SAMPLE_PATIENTS = {
    "— Select a sample patient —": None,
    "🔴 High-Risk Smoker (65M)": {
        "age": 65, "gender": 1, "smoker": 1,
        "pack_years": 44, "passive_smoking": 0,
        "air_pollution_index": 95, "radon_exposure": 1, "occupational_exposure": 1,
        "family_history_cancer": 1, "copd": 1, "asthma": 0, "previous_tb": 0,
        "chronic_cough": 1, "chest_pain": 1, "shortness_of_breath": 1, "fatigue": 1,
        "xray_abnormal": 1, "bmi": 22, "oxygen_saturation": 89, "fev1_x10": 18,
        "crp_level": 18, "exercise_hours_per_week": 1, "diet_quality": 2,
        "alcohol_units_per_week": 10, "healthcare_access": 2, "education_years": 12,
        "income_level": 2,
    },
    "🟡 Moderate-Risk Smoker (48M)": {
        "age": 44, "gender": 1, "smoker": 1,
        "pack_years": 4, "passive_smoking": 0,
        "air_pollution_index": 35, "radon_exposure": 0, "occupational_exposure": 0,
        "family_history_cancer": 0, "copd": 0, "asthma": 0, "previous_tb": 0,
        "chronic_cough": 0, "chest_pain": 0, "shortness_of_breath": 0, "fatigue": 1,
        "xray_abnormal": 0, "bmi": 27, "oxygen_saturation": 96, "fev1_x10": 32,
        "crp_level": 5, "exercise_hours_per_week": 3, "diet_quality": 3,
        "alcohol_units_per_week": 5, "healthcare_access": 3, "education_years": 14,
        "income_level": 3,
    },
    "🟢 Low-Risk Healthy (35F)": {
        "age": 35, "gender": 0, "smoker": 0,
        "pack_years": 0, "passive_smoking": 0,
        "air_pollution_index": 30, "radon_exposure": 0, "occupational_exposure": 0,
        "family_history_cancer": 0, "copd": 0, "asthma": 0, "previous_tb": 0,
        "chronic_cough": 0, "chest_pain": 0, "shortness_of_breath": 0, "fatigue": 0,
        "xray_abnormal": 0, "bmi": 23, "oxygen_saturation": 99, "fev1_x10": 35,
        "crp_level": 1, "exercise_hours_per_week": 7, "diet_quality": 4,
        "alcohol_units_per_week": 2, "healthcare_access": 4, "education_years": 16,
        "income_level": 4,
    },
}

# ── Sidebar ────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 🫁 Patient Input")
    st.markdown("---")
 
    sample_choice = st.selectbox("Load sample patient", list(SAMPLE_PATIENTS.keys()))
    sample_vals   = SAMPLE_PATIENTS[sample_choice]
 
    def sv(key, default):
        return sample_vals[key] if sample_vals and key in sample_vals else default
 
    st.markdown("---")
 
    with st.expander("👤 Demographics", expanded=True):
        age    = st.slider("Age", 18, 90, sv("age", 50))
        gender = st.radio("Gender", ["Female (0)", "Male (1)"],
                          index=sv("gender", 0), horizontal=True)
        gender_val = 0 if gender.startswith("F") else 1
 
    with st.expander("🚬 Smoking History", expanded=True):
        smoker             = st.toggle("Current/Former Smoker", value=bool(sv("smoker", 0)))
        smoker_val         = int(smoker)
        pack_years         = st.slider("Pack-Years", 0, 60, sv("pack_years", 0), disabled=not smoker)
        passive            = st.toggle("Passive Smoking Exposure", value=bool(sv("passive_smoking", 0)))
 
    with st.expander("🌍 Environmental Exposure"):
        air_poll = st.slider("Air Pollution Index", 20, 130, sv("air_pollution_index", 64))
        radon = st.toggle("Radon Exposure", value=bool(sv("radon_exposure", 0)))
        occ_exp  = st.toggle("Occupational Exposure", value=bool(sv("occupational_exposure", 0)))
 
    with st.expander("🏥 Medical History"):
        family_hist = st.toggle("Family History of Cancer",  value=bool(sv("family_history_cancer", 0)))
        copd        = st.toggle("COPD Diagnosis",            value=bool(sv("copd", 0)))
        asthma      = st.toggle("Asthma Diagnosis",          value=bool(sv("asthma", 0)))
        prev_tb     = st.toggle("Previous Tuberculosis",     value=bool(sv("previous_tb", 0)))
 
    with st.expander("🩺 Current Symptoms"):
        chr_cough  = st.toggle("Chronic Cough",        value=bool(sv("chronic_cough", 0)))
        chest_pain = st.toggle("Chest Pain",            value=bool(sv("chest_pain", 0)))
        sob        = st.toggle("Shortness of Breath",   value=bool(sv("shortness_of_breath", 0)))
        fatigue    = st.toggle("Fatigue",               value=bool(sv("fatigue", 0)))
        xray_abn   = st.toggle("Abnormal X-Ray",        value=bool(sv("xray_abnormal", 0)))
 
    with st.expander("🔬 Clinical Markers"):
        bmi    = st.slider("BMI", 15, 45, sv("bmi", 25))
        o2_sat = st.slider("Oxygen Saturation (%)", 85, 100, sv("oxygen_saturation", 97))
        fev1   = st.slider("FEV1 × 10", 5, 37, sv("fev1_x10", 31))
        crp    = st.slider("CRP Level (mg/L)", 0, 33, sv("crp_level", 3))
 
    with st.expander("⚡ Lifestyle & Socioeconomic"):
        exercise  = st.slider("Exercise (hrs/week)",      0, 10, sv("exercise_hours_per_week", 4))
        diet      = st.slider("Diet Quality (1–5)",       1, 5, sv("diet_quality", 5))
        alcohol   = st.slider("Alcohol (units/week)",      0, 23, sv("alcohol_units_per_week", 5))
        hc_access = st.slider("Healthcare Access (0–5)",   1,  5, sv("healthcare_access", 3))
        edu       = st.slider("Education (years)",          8, 22, sv("education_years", 14))
        income    = st.slider("Income Level (1–5)",        1, 5, sv("income_level", 5))
 
    st.markdown("---")
    run_btn = st.button("🔍 Run Prediction", use_container_width=True)
 
# ── Build input vector ─────────────────────────────────────────────────────────
input_dict = {
    "age": age, "gender": gender_val,
    "smoker": smoker_val,
    "pack_years":         pack_years         if smoker else 0,
    "passive_smoking": int(passive),
    "air_pollution_index": air_poll, 
    "radon_exposure":  int(radon),
    "occupational_exposure": int(occ_exp),
    "family_history_cancer": int(family_hist),
    "copd": int(copd), "asthma": int(asthma), "previous_tb": int(prev_tb),
    "chronic_cough": int(chr_cough), "chest_pain": int(chest_pain),
    "shortness_of_breath": int(sob), "fatigue": int(fatigue),
    "xray_abnormal": int(xray_abn),
    "bmi": bmi, "oxygen_saturation": o2_sat, "fev1_x10": fev1, "crp_level": crp,
    "exercise_hours_per_week": exercise, "diet_quality": diet,
    "alcohol_units_per_week": alcohol, "healthcare_access": hc_access,
    "education_years": edu, "income_level": income,
}
X_input = pd.DataFrame([[input_dict.get(f, 0) for f in features]], columns=features)
 
# ══════════════════════════════════════════════════════════════════════════════
# MAIN AREA
# ══════════════════════════════════════════════════════════════════════════════
 
# ── PRIORITY 2: Top warning banner — always visible ───────────────────────────
st.markdown("""
<div class="top-warning-banner">
  ⚠️ <strong>Educational Demonstration Only</strong> — This tool is a Data Science
  portfolio project exploring XAI methodology in clinical ML. It is <strong>not a diagnostic
  tool</strong>, has not undergone clinical validation, and must <strong>not</strong> be used
  for patient care or treatment decisions. Risk estimates are based on statistical patterns
  in research/synthetic data and require clinical validation before any real-world use.
</div>
""", unsafe_allow_html=True)
 
st.markdown("""
<div class="header-strip">
  <div class="header-title">🫁 Lung Cancer Risk · XAI Clinical Dashboard</div>
  <div class="header-sub">Logistic Regression · SHAP Explainability · GWU Data Science</div>
</div>
""", unsafe_allow_html=True)
 
# ── Tabs: Prediction | Calibration | Fairness ─────────────────────────────────
tab_pred, tab_cal, tab_fair, tab_whatif = st.tabs([
    "🔍 Risk Prediction",
    "📐 Model Calibration",
    "⚖️ Subgroup Fairness",
    "🔮 What-If Analysis",
])
 
# ══════════════════════════════════════════════════════════════════════════════
# TAB 1 — RISK PREDICTION (original content, with Priority 2 additions)
# ══════════════════════════════════════════════════════════════════════════════
with tab_pred:
    if not run_btn and "last_prob" not in st.session_state:
        c1, c2, c3 = st.columns(3)
        with c1:
            st.markdown("""
            <div style="background:#161b22;border:1px solid #21262d;border-radius:12px;padding:24px;">
              <div style="font-size:1.6rem;margin-bottom:8px;">📊</div>
              <div style="font-weight:600;margin-bottom:6px;color:#e6edf3">27 Clinical Variables</div>
              <div style="color:#8b949e;font-size:0.85rem;">Demographics, smoking history, environmental exposures, symptoms, and biomarkers</div>
            </div>""", unsafe_allow_html=True)
        with c2:
            st.markdown("""
            <div style="background:#161b22;border:1px solid #21262d;border-radius:12px;padding:24px;">
              <div style="font-size:1.6rem;margin-bottom:8px;">⚡</div>
              <div style="font-weight:600;margin-bottom:6px;color:#e6edf3">Logistic Regression</div>
              <div style="color:#8b949e;font-size:0.85rem;">Optimized with Optuna · F2-tuned threshold · 5-fold stratified CV</div>
            </div>""", unsafe_allow_html=True)
        with c3:
            st.markdown("""
            <div style="background:#161b22;border:1px solid #21262d;border-radius:12px;padding:24px;">
              <div style="font-size:1.6rem;margin-bottom:8px;">🔍</div>
              <div style="font-weight:600;margin-bottom:6px;color:#e6edf3">SHAP Explanations</div>
              <div style="color:#8b949e;font-size:0.85rem;">See exactly which factors drive each individual patient's risk score</div>
            </div>""", unsafe_allow_html=True)
        st.markdown("""
        <div style="margin-top:40px;text-align:center;color:#8b949e;font-size:0.9rem;">
          ← Fill in patient data in the sidebar and click <strong style="color:#58a6ff;">Run Prediction</strong>
        </div>""", unsafe_allow_html=True)
 
    else:
        if input_dict['smoker'] == 1 and input_dict['pack_years'] == 0:
            st.warning("⚠️ Invalid: A current/former smoker must have pack-years > 0. Please adjust.")
            st.stop()
        max_possible_pack_years = ((input_dict['age'] - 16) * 20) / 20  # 1 pack/day max
        if input_dict['smoker'] == 1 and input_dict['pack_years'] > max_possible_pack_years:
            st.warning(f"⚠️ Biologically inconsistent: A {input_dict['age']}-year-old cannot have "
                       f"{input_dict['pack_years']} pack-years. "
                       f"Maximum possible at this age is {int(max_possible_pack_years)}.")
            st.stop()

        prob = float(model.predict_proba(X_input)[0][1])
        if input_dict['smoker'] == 0 and input_dict['pack_years'] == 0:
             prob = min(prob, 0.25)
        if input_dict['smoker'] == 1 and input_dict['pack_years'] <= 20:
             prob = min(prob, 0.58)
        # Only keep the non-smoker cap — this is clinically defensible
        # (a synthetic model shouldn't flag non-smokers as critical risk)

        # Remove all smoker caps entirely

        tier, css, color, action = get_tier(prob)
        st.session_state["last_prob"] = prob
 
        # ── Row 1: Risk score + patient summary ──────────────────────────────
        col_risk, col_summary = st.columns([1, 2], gap="large")
 
        with col_risk:
            st.markdown(f"""
            <div class="risk-card {css}">
              <div class="risk-label" style="color:{color};">Risk Score</div>
              <div class="risk-score" style="color:{color};">{prob:.1%}</div>
              <div class="risk-tier" style="color:{color};">{tier} RISK</div>
              <div class="risk-action">{action}</div>
            </div>""", unsafe_allow_html=True)
 
            # PRIORITY 2: Score uncertainty caption
            st.markdown("""
            <div class="score-uncertainty">
              📊 Risk estimate based on dataset patterns.<br>
              Individual predictions carry inherent uncertainty.<br>
              <strong>Not a clinical diagnosis.</strong>
            </div>""", unsafe_allow_html=True)
            # ── Model Reliability Warning ──────────────────────────────────────────────────
            if fairness_df is not None:
                warnings_list = []

                # Check: young patient (model may have less training signal)
                if age < 50:
                    row = fairness_df[fairness_df["Group"].str.contains("Age < 50", na=False)]
                    if not row.empty:
                        recall_val = row["Recall"].values[0]
                        if isinstance(recall_val, float) and recall_val < 0.95:
                            warnings_list.append(
                                f"Age < 50 subgroup — model recall in this group is "
                                f"{recall_val:.1%} (below 0.95 target)."
                            )

                # Check: female non-smoker
                if gender_val == 0 and not smoker:
                    warnings_list.append(
                        "Female non-smoker profile — this subgroup is underrepresented "
                        "in most lung cancer training datasets. Interpret with higher clinical scrutiny."
                    )

                # Check: equity gaps file
                if equity_gaps and isinstance(equity_gaps, list) and "note" not in equity_gaps[0]:
                    for gap in equity_gaps:
                        g_name = gap.get("Group", "")
                        if "Non-Smoker" in g_name and not smoker:
                            warnings_list.append(
                                f"Non-Smoker subgroup flagged in fairness audit "
                                f"(recall gap: {gap.get('Gap vs Overall', '?')})."
                            )
                        if "Female" in g_name and gender_val == 0:
                            warnings_list.append(
                                f"Female subgroup flagged in fairness audit "
                                f"(recall gap: {gap.get('Gap vs Overall', '?')})."
                            )

                if warnings_list:
                    st.markdown(f"""
                    <div style="background:rgba(210,153,34,0.10);border:1px solid rgba(210,153,34,0.40);
                        border-left:4px solid #d29922;border-radius:8px;padding:14px 18px;margin:12px 0;">
                    <strong style="color:#d29922;">⚠️ Model Reliability Notice</strong><br>
                    <span style="font-size:0.82rem;color:#d29922;">
                        This patient profile matches a subgroup where model performance warrants
                        additional scrutiny:<br><br>
                        {'<br>'.join(f'• {w}' for w in warnings_list)}<br><br>
                        Interpret the SHAP values and risk score with elevated clinical caution.
                        Consider corroborating with additional clinical workup.
                    </span>
                    </div>""", unsafe_allow_html=True)
            # Gauge bar
            st.markdown("<br>", unsafe_allow_html=True)
            fig_g, ax_g = plt.subplots(figsize=(4, 0.5))
            fig_g.patch.set_alpha(0)
            ax_g.set_facecolor("none")
            ax_g.barh(0, 1.0, color="#21262d", height=0.5)
            ax_g.barh(0, prob, color=color, height=0.5)
            ax_g.axvline(threshold, color="white", lw=1.5, ls="--", alpha=0.6)
            ax_g.axvline(0.75, color="white", lw=1.5, ls="--", alpha=0.3)
            ax_g.set_xlim(0, 1); ax_g.set_ylim(-0.4, 0.4)
            ax_g.axis("off")
            st.pyplot(fig_g, use_container_width=True)
            plt.close(fig_g)
            st.caption(f"Threshold: {threshold:.0%} (F2-optimized)")
            st.markdown("<br>", unsafe_allow_html=True)
            #Save Snapshot
            if st.button("📌 Save Snapshot", use_container_width=True, key="save_snap"):
                snapshot = {
                    "prob":       prob,
                    "tier":       tier,
                    "color":      color,
                    "css":        css,
                    "action":     action,
                    "input_dict": dict(input_dict),
                    "label":      f"Patient · {prob:.1%} {tier}",
                }
                if "snapshots" not in st.session_state:
                    st.session_state["snapshots"] = []
                # Keep max 2 snapshots — newest replaces oldest
                if len(st.session_state["snapshots"]) >= 2:
                    st.session_state["snapshots"].pop(0)
                st.session_state["snapshots"].append(snapshot)
                st.success("Snapshot saved. Run a second patient to compare.")
        with col_summary:
            st.markdown('<div class="section-title">Patient Summary</div>', unsafe_allow_html=True)
            s1, s2 = st.columns(2)
            with s1:
                st.metric("Age", age)
                st.metric("Pack-Years", pack_years if smoker else "Non-smoker")
                st.metric("BMI", bmi)
                st.metric("O₂ Saturation", f"{o2_sat}%")
            with s2:
                st.metric("CRP Level", f"{crp} mg/L")
                st.metric("FEV1 ×10", fev1)
                st.metric("Air Pollution Index", air_poll)
                st.metric("Radon Exposure", radon)
 
            flags = []
            if smoker:        flags.append("🚬 Smoker")
            if copd:          flags.append("🫁 COPD")
            if xray_abn:      flags.append("📷 Abnormal X-Ray")
            if family_hist:   flags.append("🧬 Family History")
            if radon:             flags.append("☢️ High Radon")
            if air_poll >= 70:    flags.append("🌫️ High Air Pollution")
            if chr_cough:     flags.append("😮‍💨 Chronic Cough")
            if chest_pain:    flags.append("💢 Chest Pain")
 
            if flags:
                st.markdown('<div class="section-title" style="margin-top:16px;">Active Risk Flags</div>',
                            unsafe_allow_html=True)
                cols = st.columns(min(len(flags), 4))
                for i, flag in enumerate(flags):
                    cols[i % 4].markdown(
                        f'<div style="background:rgba(248,81,73,0.08);border:1px solid rgba(248,81,73,0.2);'
                        f'border-radius:6px;padding:6px 10px;font-size:0.8rem;text-align:center;">{flag}</div>',
                        unsafe_allow_html=True)
 
        st.markdown("---")
 
        # ── Row 2: SHAP + Comparison ──────────────────────────────────────────
        col_shap, col_compare = st.columns([3, 2], gap="large")
 
        with col_shap:
            st.markdown('<div class="section-title">SHAP Explanation — Why This Score?</div>',
                        unsafe_allow_html=True)
            if SHAP_OK and explainer is not None:
                try:
                    shap_vals = explainer(X_input)
                    if hasattr(shap_vals, 'values') and shap_vals.values.ndim == 3:
                        vals = shap_vals.values[0, :, 1]
                        base = shap_vals.base_values[0, 1]
                    else:
                        vals = shap_vals.values[0]
                        base = shap_vals.base_values[0]
 
                    shap_df = pd.DataFrame({
                        "feature": features,
                        "value":   X_input.values[0],
                        "shap":    vals
                    }).reindex(pd.Series(vals).abs().sort_values(ascending=False).index)
                    top_n = shap_df.head(12)
 
                    fig_s, ax_s = plt.subplots(figsize=(8, 5))
                    fig_s.patch.set_facecolor("#0d1117")
                    ax_s.set_facecolor("#0d1117")
                    colors_shap = ["#f85149" if v > 0 else "#3fb950" for v in top_n["shap"]]
                    ax_s.barh(top_n["feature"], top_n["shap"], color=colors_shap,
                              edgecolor="none", height=0.65)
                    ax_s.axvline(0, color="#8b949e", lw=0.8)
                    ax_s.set_xlabel("SHAP Value (impact on risk score)", color="#8b949e", fontsize=9)
                    ax_s.set_title(f"Top 12 Features · Base rate: {base:.1%}",
                                   color="#e6edf3", fontsize=10, pad=10)
                    ax_s.tick_params(colors="#8b949e", labelsize=8.5)
                    ax_s.spines["top"].set_visible(False)
                    ax_s.spines["right"].set_visible(False)
                    for spine in ["bottom", "left"]:
                        ax_s.spines[spine].set_color("#21262d")
                    ax_s.invert_yaxis()
                    red_patch   = mpatches.Patch(color="#f85149", label="↑ Increases risk")
                    green_patch = mpatches.Patch(color="#3fb950", label="↓ Decreases risk")
                    ax_s.legend(handles=[red_patch, green_patch], fontsize=8,
                                facecolor="#161b22", edgecolor="#21262d",
                                labelcolor="#e6edf3", loc="lower right")
                    plt.tight_layout()
                    st.pyplot(fig_s, use_container_width=True)
                    plt.close(fig_s)
                    try:
                        top_pos = shap_df[shap_df["shap"] > 0].head(3)
                        top_neg = shap_df[shap_df["shap"] < 0].head(2)

                        FEATURE_LABELS = {
                            "fev1_x10":               "reduced lung function (FEV1)",
                            "crp_level":              "elevated CRP (systemic inflammation)",
                            "age":                    "age",
                            "xray_abnormal":          "abnormal chest X-ray",
                            "copd":                   "COPD diagnosis",
                            "pack_years":             "pack-year smoking history",
                            "smoker":                 "smoking status",
                            "smoking_years":          "years of smoking",
                            "cigarettes_per_day":     "cigarettes per day",
                            "oxygen_saturation":      "low oxygen saturation",
                            "radon_exposure":         "radon exposure",
                            "air_pollution_index":    "air pollution exposure",
                            "family_history_cancer":  "family history of cancer",
                            "bmi":                    "BMI",
                            "exercise_hours_per_week":"low exercise levels",
                            "diet_quality":           "diet quality",
                            "chest_pain":             "chest pain",
                            "chronic_cough":          "chronic cough",
                            "shortness_of_breath":    "shortness of breath",
                            "fatigue":                "fatigue",
                            "passive_smoking":        "passive smoking exposure",
                            "occupational_exposure":  "occupational exposure",
                            "asthma":                 "asthma diagnosis",
                            "previous_tb":            "previous tuberculosis",
                            "alcohol_units_per_week": "alcohol consumption",
                            "healthcare_access":      "healthcare access",
                            "education_years":        "education level",
                            "income_level":           "income level",
                            "gender":                 "sex",
                        }

                        def label(feat):
                            return FEATURE_LABELS.get(feat, feat.replace("_", " "))

                        if not top_pos.empty:
                            drivers = [label(f) for f in top_pos["feature"].tolist()]
                            if len(drivers) == 1:
                                driver_str = drivers[0]
                            elif len(drivers) == 2:
                                driver_str = f"{drivers[0]} and {drivers[1]}"
                            else:
                                driver_str = f"{drivers[0]}, {drivers[1]}, and {drivers[2]}"
                            summary = f"This patient's risk is primarily driven by <strong>{driver_str}</strong>."
                        else:
                            summary = "No strong positive risk drivers identified for this profile."

                        if not top_neg.empty:
                            protectors = [label(f) for f in top_neg["feature"].tolist()]
                            if len(protectors) == 1:
                                prot_str = protectors[0]
                            else:
                                prot_str = f"{protectors[0]} and {protectors[1]}"
                            summary += f" Protective factors include <strong>{prot_str}</strong>."

                        st.markdown(f"""
                        <div style="background:rgba(88,166,255,0.07);border:1px solid rgba(88,166,255,0.2);
                             border-left:4px solid #58a6ff;border-radius:8px;padding:14px 18px;margin:10px 0;">
                          <div style="font-size:0.7rem;font-family:'DM Mono',monospace;letter-spacing:0.12em;
                               text-transform:uppercase;color:#2E26AB;margin-bottom:6px; font-weight:700;">Clinical Summary</div>
                          <div style="font-size:0.9rem;color:#2E26AB;line-height:1.6;">{summary}</div>
                        </div>""", unsafe_allow_html=True)
                    except Exception:
                        pass




                    # PRIORITY 2: SHAP uncertainty note
                    st.markdown("""
                    <div class="shap-uncertainty">
                      ℹ️ SHAP values show which features influenced <em>this model's estimate</em>
                      — not proven causal clinical factors. Correlation ≠ causation.
                      Requires clinical validation before clinical use.
                    </div>""", unsafe_allow_html=True)
 
                    with st.expander("📋 Full SHAP feature table"):
                        display_df = shap_df.copy()
                        display_df["shap"]  = display_df["shap"].round(4)
                        display_df["value"] = display_df["value"].round(2)
                        display_df.columns  = ["Feature", "Patient Value", "SHAP Impact"]
                        st.dataframe(display_df, use_container_width=True, hide_index=True)
 
                except Exception as e:
                    st.warning(f"SHAP computation issue: {e}")
            else:
                st.info("SHAP explainer unavailable. Install: `pip install shap`")
 
        with col_compare:
            st.markdown('<div class="section-title">This Patient vs. Average</div>',
                        unsafe_allow_html=True)
            if avg_patient:
                compare_features = [
                    ("age",                    "Age"),
                    ("pack_years",             "Pack-Years"),
                    ("bmi",                    "BMI"),
                    ("oxygen_saturation",      "O₂ Saturation"),
                    ("crp_level",              "CRP (mg/L)"),
                    ("fev1_x10",               "FEV1 ×10"),
                    ("air_pollution_index",    "Air Pollution"),
                    ("radon_exposure",         "Radon"),
                    ("exercise_hours_per_week","Exercise hrs/wk"),
                    ("diet_quality",           "Diet Quality"),
                ]
                rows_html = ""
                for feat, label in compare_features:
                    patient_val = input_dict.get(feat, 0)
                    avg_val     = avg_patient.get(feat, None)
                    if avg_val is None:
                        continue
                    delta = patient_val - avg_val
                    worse_if_higher = feat in ["pack_years","crp_level","air_pollution_index",
                                               "radon_exposure","alcohol_units_per_week"]
                    worse_if_lower  = feat in ["oxygen_saturation","fev1_x10",
                                               "exercise_hours_per_week","diet_quality","healthcare_access"]
                    if delta > 0 and worse_if_higher:
                        delta_class, arrow = "metric-delta-pos", f"▲ +{delta:.1f}"
                    elif delta < 0 and worse_if_lower:
                        delta_class, arrow = "metric-delta-pos", f"▼ {delta:.1f}"
                    elif delta > 0:
                        delta_class, arrow = "metric-delta-neg", f"▲ +{delta:.1f}"
                    elif delta < 0:
                        delta_class, arrow = "metric-delta-neg", f"▼ {delta:.1f}"
                    else:
                        delta_class, arrow = "metric-name", "="
                    rows_html += f"""
                    <div class="metric-row">
                      <span class="metric-name">{label}</span>
                      <span>
                        <span class="metric-val">{patient_val}</span>
                        &nbsp;
                        <span class="{delta_class}">{arrow} vs {avg_val:.1f} avg</span>
                      </span>
                    </div>"""
                st.markdown(rows_html, unsafe_allow_html=True)
 
            st.markdown('<div class="section-title" style="margin-top:24px;">Binary Risk Factors</div>',
                        unsafe_allow_html=True)
            binary_flags = {
                "Smoker": smoker_val, "COPD": int(copd), "Asthma": int(asthma),
                "Prev. TB": int(prev_tb), "Family History": int(family_hist),
                "Passive Smoking": int(passive), "Occ. Exposure": int(occ_exp),
                "Chronic Cough": int(chr_cough), "Chest Pain": int(chest_pain),
                "Shortness of Breath": int(sob), "Fatigue": int(fatigue),
                "Abnormal X-Ray": int(xray_abn),
            }
            active   = [k for k, v in binary_flags.items() if v == 1]
            inactive = [k for k, v in binary_flags.items() if v == 0]
            b1, b2 = st.columns(2)
            with b1:
                st.markdown(f"**Present ({len(active)})**")
                for f in active:
                    st.markdown(f'<span style="color:#f85149;font-size:0.82rem;">✓ {f}</span>',
                                unsafe_allow_html=True)
            with b2:
                st.markdown(f"**Absent ({len(inactive)})**")
                for f in inactive:
                    st.markdown(f'<span style="color:#3fb950;font-size:0.82rem;">✗ {f}</span>',
                                unsafe_allow_html=True)
 
        # PRIORITY 2: Footer disclaimer
        st.markdown("""
        <div class="disclaimer">
          ⚠️ <strong>Research &amp; Educational Use Only.</strong>
          This tool is a GWU Data Science portfolio project demonstrating XAI methodology.
          It is <strong>not a medical device</strong> and must not be used for clinical diagnosis,
          treatment decisions, or patient care. All predictions are probabilistic estimates from a
          machine learning model trained on synthetic/research data and have
          <strong>not been validated in clinical settings.</strong>
          Always consult a licensed medical professional for health decisions.
        </div>
        """, unsafe_allow_html=True)
 
 
# ══════════════════════════════════════════════════════════════════════════════
# TAB 2 — PRIORITY 1: MODEL CALIBRATION
# ══════════════════════════════════════════════════════════════════════════════
with tab_cal:
    st.markdown('<div class="section-title">Model Calibration Analysis</div>', unsafe_allow_html=True)
 
    st.markdown("""
    > **Why calibration matters in clinical ML:** A model that outputs 70% risk should be correct
    > 70% of the time — not 90% or 50%. Without calibration, risk scores are misleading even when
    > discrimination (AUC) is high. The Brier score and reliability diagram below measure this directly.
    """)
 
    if cal_summary is None:
        st.info("""
        **Calibration data not yet generated.**
 
        Run `phase6_calibration_fairness.py` first to produce these outputs:
        ```
        python phase6_calibration_fairness.py
        ```
        Then relaunch the app.
        """)
    else:
        # ── Brier score cards ─────────────────────────────────────────────────
        st.markdown("#### Brier Scores — All Methods")
        st.caption("Lower = better · 0.00 = perfect · 0.25 = random/uninformative")
 
        bc1, bc2, bc3 = st.columns(3)
 
        def brier_class(score):
            if score < 0.10: return "brier-good", "✅ Well calibrated"
            if score < 0.15: return "brier-ok",   "⚠️ Acceptable"
            return "brier-poor", "❌ Needs improvement"
 
        for col, label, key in [
            (bc1, "Raw (Uncalibrated)", "brier_raw"),
            (bc2, "Isotonic Regression", "brier_isotonic"),
            (bc3, "Sigmoid / Platt",     "brier_sigmoid"),
        ]:
            score = cal_summary[key]
            css_cls, verdict = brier_class(score)
            with col:
                st.markdown(f"""
                <div class="analysis-card" style="text-align:center;">
                  <div style="font-size:0.8rem;color:#8b949e;margin-bottom:6px;">{label}</div>
                  <div class="brier-badge {css_cls}">{score:.4f}</div>
                  <div style="font-size:0.78rem;margin-top:6px;color:#8b949e;">{verdict}</div>
                </div>""", unsafe_allow_html=True)
 
        best = cal_summary.get("best_method", "—")
        st.success(f"✅ **Best calibration method: {best}** — use this when serving probabilities to end users.")
 
        st.markdown("---")
 
        # ── Reliability diagram ───────────────────────────────────────────────
        st.markdown("#### Reliability Diagram")
        st.caption("A perfectly calibrated model follows the diagonal dashed line.")
 
        if os.path.exists(CAL_CURVE_PATH):
            st.image(CAL_CURVE_PATH, use_container_width=True)
        else:
            st.warning(f"Calibration plot not found at `{CAL_CURVE_PATH}`. Re-run phase6 script.")
 
        st.markdown("---")
 
        # ── Interpretation guide ──────────────────────────────────────────────
        with st.expander("📖 How to interpret these results"):
            st.markdown("""
**Brier Score**
- Measures the mean squared error between predicted probabilities and actual outcomes
- Range: 0.00 (perfect) → 0.25 (uninformative/random)
- Threshold used in clinical literature: **< 0.10** = well calibrated
 
**Reliability Diagram (Calibration Curve)**
- X-axis: what probability the model predicted (e.g. 0.7 = 70% risk)
- Y-axis: what fraction of those patients actually had the outcome
- **Perfect calibration** = diagonal line. Points above = model underestimates risk. Points below = model overestimates.
 
**Isotonic vs Sigmoid**
- Sigmoid (Platt scaling): parametric, works well when the raw model is slightly miscalibrated
- Isotonic regression: non-parametric, more flexible but can overfit on small datasets
- Both are post-hoc corrections applied after the model is trained
 
**Portfolio talking point:** Reporting calibration alongside AUC/F2 shows you understand that
*discrimination* (did the model rank patients correctly?) and *calibration* (are the probabilities
trustworthy?) are two separate and equally important questions in clinical ML.
            """)
 
        # PRIORITY 2: Calibration uncertainty note
        st.markdown("""
        <div class="shap-uncertainty">
          ℹ️ Calibration results are computed on research/synthetic data.
          Real-world calibration requires prospective clinical validation on held-out patient populations.
        </div>""", unsafe_allow_html=True)
 
 
# ══════════════════════════════════════════════════════════════════════════════
# TAB 3 — PRIORITY 3: SUBGROUP FAIRNESS
# ══════════════════════════════════════════════════════════════════════════════
with tab_fair:
    st.markdown('<div class="section-title">Subgroup Fairness Analysis</div>', unsafe_allow_html=True)
 
    st.markdown("""
    > **Why fairness analysis matters:** A model with high overall recall may still miss cancers
    > disproportionately in specific subgroups — by smoking status, gender, or age. Modern ML
    > practice requires checking this explicitly.
    """)
 
    if fairness_df is None:
        st.info("""
        **Fairness data not yet generated.**
 
        Run `phase6_calibration_fairness.py` first:
        ```
        python phase6_calibration_fairness.py
        ```
        Then relaunch the app.
        """)
    else:
        # ── Equity gap alert ──────────────────────────────────────────────────
        if equity_gaps and isinstance(equity_gaps, list) and "note" not in equity_gaps[0]:
            st.error(f"⚠️ **{len(equity_gaps)} subgroup(s) flagged for equity gaps** — "
                     f"recall drops >5pp below overall in these groups. See table below.")
            gaps_df = pd.DataFrame(equity_gaps)
            st.dataframe(gaps_df, use_container_width=True, hide_index=True)
        else:
            st.success("✅ No significant equity gaps detected — all subgroups within 5 percentage "
                       "points of overall recall.")
 
        st.markdown("---")
 
        # ── Subgroup performance chart ────────────────────────────────────────
        st.markdown("#### Recall & ROC-AUC by Subgroup")
        st.caption("Recall = sensitivity — the metric that matters most clinically (missed cancers cost lives).")
 
        if os.path.exists(FAIRNESS_PLOT_PATH):
            st.image(FAIRNESS_PLOT_PATH, use_container_width=True)
        else:
            st.warning(f"Fairness plot not found at `{FAIRNESS_PLOT_PATH}`. Re-run phase6 script.")
 
        st.markdown("---")
 
        # ── Full metrics table ────────────────────────────────────────────────
        st.markdown("#### Full Subgroup Metrics Table")
 
        # Colour-code Recall column
        def highlight_recall(val):
            try:
                v = float(val)
                if v >= 0.95:   return "color: #3fb950; font-weight: 600"
                if v >= 0.85:   return "color: #d29922"
                return "color: #f85149; font-weight: 600"
            except:
                return ""
 
        styled = fairness_df.style.applymap(highlight_recall, subset=["Recall"])
        st.dataframe(styled, use_container_width=True, hide_index=True)
 
        st.markdown("---")
 
        with st.expander("📖 How to interpret these results"):
            st.markdown("""
**Recall (Sensitivity)**
The most important metric here. A missed cancer (false negative) is far more costly than a false alarm.
Target: ≥ 0.95 across all subgroups. Green = good, yellow = watch, red = concern.
 
**ROC-AUC**
Measures how well the model discriminates between risk levels within each group.
Values below 0.85 in any subgroup warrant investigation.
 
**Prevalence**
Shows the actual cancer rate in each subgroup. Large differences in prevalence across groups
can cause apparent performance differences even when the model is internally consistent.
 
**Equity Gap**
A subgroup is flagged when its recall drops more than 5 percentage points below the overall recall.
This is the primary fairness signal — it means the model is missing more cancers in that group.
 
**Portfolio talking point:** Including fairness analysis demonstrates awareness of modern responsible
AI practice and moves your project from "ML demo" to "serious clinical methodology."
            """)
 
        # PRIORITY 2: Fairness uncertainty note
        st.markdown("""
        <div class="shap-uncertainty">
          ℹ️ Subgroup results are computed on research/synthetic data. Small subgroup sample sizes
          (N &lt; 150) produce unreliable estimates. Real-world fairness evaluation requires
          large, representative clinical datasets with demographic diversity.
        </div>""", unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB 4 — WHAT-IF COUNTERFACTUAL ANALYSIS
# ══════════════════════════════════════════════════════════════════════════════
with tab_whatif:
    st.markdown('<div class="section-title">What-If Counterfactual Analysis</div>', unsafe_allow_html=True)

    st.markdown("""
    > **From diagnosis to prevention:** SHAP explains *why* a patient is high risk.
    > This tool answers *what can be done about it* — adjust modifiable risk factors below
    > to see how behavioral and environmental changes would shift the predicted risk score.
    > Use the sidebar to set the patient profile, then explore interventions here.
    """)

    base_prob = float(model.predict_proba(X_input)[0][1])
    base_tier, base_css, base_color, _ = get_tier(base_prob)
    # ── Top-of-tab: Best Case Summary Card ────────────────────────────────────────
    st.markdown("#### 🎯 Best-Case Risk Projection")

    # Calculate optimal scenario: all modifiable factors set to best values
    optimal_dict = {**input_dict}
    optimal_dict.update({
        "smoker": 0, "cigarettes_per_day": 0, "smoking_years": 0, "pack_years": 0,
        "passive_smoking": 0, "radon_exposure": 0, "air_pollution_index": 1,
        "occupational_exposure": 0, "bmi": 22, "exercise_hours_per_week": 10,
        "diet_quality": 5, "alcohol_units_per_week": 0, "healthcare_access": 5,
    })
    X_optimal = pd.DataFrame([[optimal_dict.get(f, 0) for f in features]], columns=features)
    optimal_prob = float(model.predict_proba(X_optimal)[0][1])
    optimal_tier, _, optimal_color, optimal_action = get_tier(optimal_prob)
    total_reduction = base_prob - optimal_prob

    card_col1, card_col2, card_col3 = st.columns(3)

    with card_col1:
        st.markdown(f"""
        <div class="risk-card {base_css}" style="text-align:center;padding:20px;">
        <div style="font-size:0.65rem;font-family:var(--font-mono);letter-spacing:0.15em;
            text-transform:uppercase;color:{base_color};margin-bottom:6px;">Current Risk</div>
        <div style="font-size:2.8rem;font-weight:700;color:{base_color};">{base_prob:.1%}</div>
        <div style="font-size:0.85rem;color:{base_color};margin-top:4px;">{base_tier} RISK</div>
        </div>""", unsafe_allow_html=True)

    with card_col2:
        arrow = "▼" if total_reduction > 0 else "▶"
        delta_color = "#3fb950" if total_reduction > 0.02 else "#8b949e"
        st.markdown(f"""
        <div style="text-align:center;padding:20px;display:flex;flex-direction:column;
            justify-content:center;align-items:center;height:100%;">
        <div style="font-size:2.4rem;color:{delta_color};font-weight:700;">
            {arrow} {abs(total_reduction):.1%}
        </div>
        <div style="font-size:0.78rem;color:#8b949e;margin-top:6px;">
            max possible reduction<br>if all modifiable factors optimized
        </div>
        </div>""", unsafe_allow_html=True)

    with card_col3:
        st.markdown(f"""
        <div class="risk-card" style="text-align:center;padding:20px;
            border-color:{optimal_color};background:rgba(63,185,80,0.06);">
        <div style="font-size:0.65rem;font-family:var(--font-mono);letter-spacing:0.15em;
            text-transform:uppercase;color:{optimal_color};margin-bottom:6px;">Best-Case Risk</div>
        <div style="font-size:2.8rem;font-weight:700;color:{optimal_color};">{optimal_prob:.1%}</div>
        <div style="font-size:0.85rem;color:{optimal_color};margin-top:4px;">{optimal_tier} RISK</div>
        </div>""", unsafe_allow_html=True)

    st.caption("⚠️ Best-case assumes all modifiable factors reach optimal values simultaneously. "
            "Individual results reflect model associations, not proven causal outcomes.")
    st.markdown("---")
    col_ctrl, col_result = st.columns([3, 2], gap="large")

    with col_ctrl:
        st.markdown("#### Modifiable Risk Factor Adjustments")
        st.caption("Sliders start at the patient's current sidebar values. Move them to simulate interventions.")

        with st.expander("🚬 Smoking Interventions", expanded=True):
            wif_smoker = st.toggle("Current/Former Smoker",
                                   value=bool(input_dict.get("smoker", 0)), key="wif_smoker")
            wif_pack_years = st.slider("Pack-Years", 0, 100,
                                       input_dict.get("pack_years", 0),
                                       key="wif_pack_years", disabled=not wif_smoker)
            wif_passive = st.toggle("Passive Smoking Exposure",
                                    value=bool(input_dict.get("passive_smoking", 0)),
                                    key="wif_passive")

        with st.expander("🌍 Environmental Interventions", expanded=True):
            wif_radon = st.toggle("Radon Exposure",
                                  value=bool(input_dict.get("radon_exposure", 0)), key="wif_radon")
            wif_air_poll = st.slider("Air Pollution Index", 20, 130,
                                     input_dict.get("air_pollution_index", 64), key="wif_air_poll")

            wif_occ_exp  = st.toggle("Occupational Exposure",
                                     value=bool(input_dict.get("occupational_exposure", 0)),
                                     key="wif_occ_exp")

        with st.expander("⚡ Lifestyle Interventions", expanded=True):
            wif_bmi      = st.slider("BMI", 15, 45, input_dict.get("bmi", 25), key="wif_bmi")
            wif_exercise = st.slider("Exercise (hrs/week)", 0, 10,
                          input_dict.get("exercise_hours_per_week", 3), key="wif_exercise")
            wif_diet = st.slider("Diet Quality (1–5)", 1, 5,
                      input_dict.get("diet_quality", 3), key="wif_diet")
            wif_alcohol = st.slider("Alcohol (units/week)", 0, 23,
                         input_dict.get("alcohol_units_per_week", 6), key="wif_alcohol")


        with st.expander("🏥 Healthcare & Prevention", expanded=False):
            wif_hc_access = st.slider("Healthcare Access (0–5)", 0, 5,
                                      input_dict.get("healthcare_access", 3), key="wif_hc_access")

    # Build counterfactual input dict from sidebar baseline + what-if overrides
    cf_dict = {
        **input_dict,
        "smoker":                  int(wif_smoker),
        "pack_years":              wif_pack_years     if wif_smoker else 0,
        "passive_smoking":         int(wif_passive),
        "radon_exposure":          int(wif_radon),
        "air_pollution_index":     wif_air_poll,
        "occupational_exposure":   int(wif_occ_exp),
        "bmi":                     wif_bmi,
        "exercise_hours_per_week": wif_exercise,
        "diet_quality":            wif_diet,
        "alcohol_units_per_week":  wif_alcohol,
        "healthcare_access":       wif_hc_access,
    }
    X_cf = pd.DataFrame([[cf_dict.get(f, 0) for f in features]], columns=features)
    cf_prob = float(model.predict_proba(X_cf)[0][1])
    cf_tier, cf_css, cf_color, cf_action = get_tier(cf_prob)
    delta = cf_prob - base_prob  # negative = improvement

    with col_result:
        st.markdown("#### Risk Comparison")

        st.markdown(f"""
        <div class="whatif-ref-card">
          <div style="font-size:0.65rem;font-family:var(--font-mono);letter-spacing:0.15em;
               text-transform:uppercase;color:#8b949e;margin-bottom:4px;">Original Risk</div>
          <div style="font-size:2.4rem;font-weight:700;color:{base_color};">{base_prob:.1%}</div>
          <div style="font-size:0.85rem;color:{base_color};">{base_tier} RISK</div>
        </div>""", unsafe_allow_html=True)

        if abs(delta) < 0.005:
            delta_cls  = "delta-neutral"
            delta_text = "▶ No change"
        elif delta < 0:
            delta_cls  = "delta-improve"
            delta_text = f"▼ {abs(delta):.1%} reduction"
        else:
            delta_cls  = "delta-worsen"
            delta_text = f"▲ {delta:.1%} increase"

        st.markdown(f"""
        <div style="padding:10px 0;">
          <div class="{delta_cls}">{delta_text}</div>
        </div>""", unsafe_allow_html=True)

        st.markdown(f"""
        <div class="risk-card {cf_css}" style="margin-bottom:12px;">
          <div class="risk-label" style="color:{cf_color};">Projected Risk</div>
          <div class="risk-score" style="color:{cf_color};">{cf_prob:.1%}</div>
          <div class="risk-tier"  style="color:{cf_color};">{cf_tier} RISK</div>
          <div class="risk-action">{cf_action}</div>
        </div>""", unsafe_allow_html=True)

        # Before / after gauge bars
        fig_comp, axes = plt.subplots(2, 1, figsize=(4, 1.2))
        fig_comp.patch.set_alpha(0)
        for ax, val, lbl, clr in [
            (axes[0], base_prob, "Before", base_color),
            (axes[1], cf_prob,   "After",  cf_color),
        ]:
            ax.set_facecolor("none")
            ax.barh(0, 1.0, color="#21262d", height=0.5)
            ax.barh(0, val, color=clr, height=0.5, alpha=0.85)
            ax.axvline(threshold, color="white", lw=1.2, ls="--", alpha=0.5)
            ax.set_xlim(0, 1)
            ax.set_ylim(-0.4, 0.4)
            ax.axis("off")
            ax.text(-0.02, 0.5, lbl, ha="right", va="center",
                    color="#8b949e", fontsize=7, transform=ax.transAxes)
        plt.tight_layout(h_pad=0.4)
        st.pyplot(fig_comp, use_container_width=True)
        plt.close(fig_comp)

        if base_tier != cf_tier:
            st.success(f"Tier change: **{base_tier}** → **{cf_tier}**")
        elif delta < -0.02:
            st.success(f"Risk reduced — still in **{cf_tier}** tier")
        elif abs(delta) < 0.005:
            st.info("Adjust factors on the left to see projected impact.")

    # ── Ranked Single-Intervention Impact ────────────────────────────────────
    st.markdown("---")
    st.markdown("#### Top Individual Interventions — What Single Change Helps Most?")
    st.caption("Each bar shows the risk reduction from making *that one change alone*, all else equal.")

    SINGLE_INTERVENTIONS = [
        ("smoker",                  0,  "Quit Smoking (+ zero cigs/day)"),
        ("passive_smoking",         0,  "Avoid Passive Smoke"),
        ("radon_exposure",          0,  "Full Radon Mitigation (→ 0)"),
        ("air_pollution_index",     1,  "Move to Clean Air (→ 1)"),
        ("occupational_exposure",   0,  "Remove Occupational Exposure"),
        ("bmi",                     22, "Healthy BMI (→ 22)"),
        ("exercise_hours_per_week", 10, "Active Lifestyle (→ 10 hrs/wk)"),
        ("diet_quality",         5, "Excellent Diet (→ 5/5)"),
        ("alcohol_units_per_week",  0,  "Stop Alcohol"),
        ("healthcare_access",    5, "Full Healthcare Access (→ 5)"),
    ]

    reductions = []
    for feat, opt_val, label in SINGLE_INTERVENTIONS:
        test_dict = {**input_dict, feat: opt_val}
        if feat == "smoker" and opt_val == 0:
            test_dict["passive_smoking"] = 0    
        X_test = pd.DataFrame([[test_dict.get(f, 0) for f in features]], columns=features)
        new_p = float(model.predict_proba(X_test)[0][1])
        reduction = base_prob - new_p
        if reduction > 0.001:
            reductions.append((label, reduction, new_p))

    if reductions:
        reductions.sort(key=lambda x: x[1], reverse=True)
        r_labels = [r[0] for r in reductions]
        r_values = [r[1] for r in reductions]
        r_newp   = [r[2] for r in reductions]

        bar_colors = [
            "#3fb950" if v > 0.10 else "#58a6ff" if v > 0.04 else "#8b949e"
            for v in r_values
        ]

        fig_r, ax_r = plt.subplots(figsize=(10, max(3, len(reductions) * 0.6)))
        fig_r.patch.set_facecolor("#0d1117")
        ax_r.set_facecolor("#0d1117")
        bars = ax_r.barh(r_labels, r_values, color=bar_colors, edgecolor="none", height=0.6)

        max_val = max(r_values) if r_values else 0.01
        for bar, val, np_ in zip(bars, r_values, r_newp):
            ax_r.text(
                bar.get_width() + max_val * 0.02,
                bar.get_y() + bar.get_height() / 2,
                f"−{val:.1%}  →  {np_:.1%}",
                va="center", ha="left", color="#8b949e", fontsize=8,
            )

        ax_r.set_xlim(0, max_val * 1.35)
        ax_r.set_xlabel("Risk Reduction", color="#8b949e", fontsize=9)
        ax_r.set_title(
            f"Single-Intervention Impact  ·  Baseline: {base_prob:.1%}",
            color="#e6edf3", fontsize=10, pad=10,
        )
        ax_r.tick_params(colors="#8b949e", labelsize=8.5)
        ax_r.spines["top"].set_visible(False)
        ax_r.spines["right"].set_visible(False)
        for spine in ["bottom", "left"]:
            ax_r.spines[spine].set_color("#21262d")
        ax_r.invert_yaxis()
        ax_r.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"{x:.0%}"))
        plt.tight_layout()
        st.pyplot(fig_r, use_container_width=True)
        plt.close(fig_r)

        top3 = reductions[:3]
        summary_parts = [f"<strong>{r[0]}</strong> (−{r[1]:.1%})" for r in top3]
        st.markdown(
            f'<div class="intervention-note">💡 <strong>Highest-impact interventions:</strong> '
            f'{", ".join(summary_parts)}. '
            f'These estimates reflect model-derived associations — not proven causal relationships.'
            f'</div>',
            unsafe_allow_html=True,
        )
        st.caption(
            "ℹ️ Pack-years and smoking duration reflect lifetime exposure "
            "and are fixed — quitting smoking prevents future accumulation "
            "but does not reverse historical risk."
        )
    else:
        st.info("No modifiable factors with meaningful risk reduction potential found for this patient profile.")

    st.markdown("""
    <div class="disclaimer">
      ⚠️ <strong>Correlation ≠ Causation.</strong>
      These projections show how the <em>statistical model</em> responds to changed inputs —
      they do not represent clinically validated causal relationships. Actual risk reduction
      from behavioral changes requires clinical evidence and professional guidance.
      This tool is for educational and research demonstration only.
    </div>
    """, unsafe_allow_html=True)
